### ISSUE TITLE
Container fails to build

### ISSUE THREAD

**Issue by dalixwill** [MicrosoftDocs/inferentialthinking#8]
Hello, 

I am unable to build the container for the Visual Studio codespace. It seems that the nbpdfexport version requirement cannot be met (see attached image). 

<img width="731" alt="Screen Shot 2020-08-01 at 2 38 32 PM" src="https://user-images.githubusercontent.com/25827848/89109203-ccd9b980-d404-11ea-9fdb-9a4582d7c3b6.png">

Complete error is provided below. Any suggestions for a work-around are appreciated.

Cheers,
-- D.A.

> 
> Collecting nb2pdf
>   Downloading nb2pdf-0.6.1-py3-none-any.whl (7.9 kB)
> ERROR: Could not find a version that satisfies the requirement nbpdfexport==0.2.2 (from nb2pdf->otter-grader) (from versions: 0.1, 0.2, 0.2.1)
> ERROR: No matching distribution found for nbpdfexport==0.2.2 (from nb2pdf->otter-grader)
> The command '/bin/sh -c apt-get update     && apt-get -y install --no-install-recommends apt-utils dialog 2>&1     && apt-get -y install git openssh-client less iproute2 procps lsb-release     && pip --disable-pip-version-check --no-cache-dir install pylint     && pip --disable-pip-version-check --no-cache-dir install jupyter     && pip --disable-pip-version-check --no-cache-dir install datascience     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install numpy     && pip --disable-pip-version-check --no-cache-dir install pandas     && pip --disable-pip-version-check --no-cache-dir install scipy     && pip --disable-pip-version-check --no-cache-dir install folium>=0.9.1     && pip --disable-pip-version-check --no-cache-dir install matplotlib     && pip --disable-pip-version-check --no-cache-dir install ipywidgets>=7.0.0     && pip --disable-pip-version-check --no-cache-dir install bqplot     && pip --disable-pip-version-check --no-cache-dir install nbinteract>=0.0.12     && pip --disable-pip-version-check --no-cache-dir install otter-grader     && pip --disable-pip-version-check --no-cache-dir install okpy      && groupadd --gid $USER_GID $USERNAME     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME     && apt-get install -y sudo     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME    && chmod 0440 /etc/sudoers.d/$USERNAME     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
> 
> docker process exited with exit code 1
> Finished: 2020-08-01T19:38:09
> The custom container could not be built.
>

**Comment by iaclarke** [comment]
Hi there

I am experiencing exactly the same issue, and so is my friend. Is there a resolution?

Many thanks
Ian

**Comment by leestott** [comment]
Hi thanks all so this looks a issue caused by a update to the otter-grader auto assessment tool let me look into this now

**Comment by leestott** [comment]
Temp fix applied by installing nb2pdf from alternative source to allow otter-grader to install

Line added to docker file

#Otter-grader fix
    Run pip install git+https://github.com/eldridgejm/nb2pdf

Install and codespaces environment now deploys

**Comment by chrispyles** [comment]
@leestott's fix should be removable with nb2pdf 0.6.2. This removes the unreleased dependency.

**Comment by leestott** [comment]
@chrispyles  thanks temp fix was removed when the fix was applied
